"use client";

import { useSession, signIn, signOut } from "next-auth/react";
import { LogOut, LogIn, User, ChevronDown, KeyRound } from "lucide-react";
import { useState, useRef, useEffect } from "react";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { clearAllLocalData } from "@/lib/store";

/**
 * Auth button shown in the top-right of the header.
 *
 * - When unauthenticated: shows "Accedi" (Login with Google) — and a
 *   secondary option "Codice Beta" for users who don't have a Google
 *   account (e.g. friends on iOS testing the app).
 *
 * - When authenticated: shows the user's avatar + name, with a dropdown
 *   containing "Esci" (Logout) that calls signOut()
 *
 * Two login flows:
 *   1. Google OAuth — full integration (sync, Gmail sending, etc.)
 *   2. Beta Code — email + 8-char code generated by the admin via
 *      /admin/beta-testers. Beta users have full app access EXCEPT
 *      Gmail-dependent features (those are auto-hidden via session flag).
 */
export function AuthButton() {
  const { data: session, status } = useSession();
  const [menuOpen, setMenuOpen] = useState(false);
  const [betaDialogOpen, setBetaDialogOpen] = useState(false);
  const [betaEmail, setBetaEmail] = useState("");
  const [betaCode, setBetaCode] = useState("");
  const [betaError, setBetaError] = useState<string | null>(null);
  const [betaLoading, setBetaLoading] = useState(false);
  const menuRef = useRef<HTMLDivElement>(null);

  // Close dropdown when clicking outside
  useEffect(() => {
    if (!menuOpen) return;
    function handleClick(e: MouseEvent) {
      if (menuRef.current && !menuRef.current.contains(e.target as Node)) {
        setMenuOpen(false);
      }
    }
    document.addEventListener("mousedown", handleClick);
    return () => document.removeEventListener("mousedown", handleClick);
  }, [menuOpen]);

  // Loading state
  if (status === "loading") {
    return <div className="w-8 h-8 rounded-full bg-muted/50 animate-pulse" />;
  }

  // Unauthenticated — show login button + beta dialog
  if (status === "unauthenticated" || !session?.user) {
    const handleBetaLogin = async () => {
      setBetaError(null);
      if (!betaEmail.trim() || !betaCode.trim()) {
        setBetaError("Inserisci email e codice.");
        return;
      }
      setBetaLoading(true);
      const result = await signIn("beta-code", {
        email: betaEmail.trim(),
        code: betaCode.trim().toUpperCase(),
        redirect: false,
      });
      setBetaLoading(false);
      if (result?.error) {
        const errMap: Record<string, string> = {
          CredentialsSignin: "Email o codice non validi, oppure codice già usato o scaduto.",
        };
        setBetaError(errMap[result.error] || `Login non riuscito: ${result.error}`);
        return;
      }
      // Success
      setBetaDialogOpen(false);
      setBetaEmail("");
      setBetaCode("");
      // Reload to trigger cloud sync
      window.location.href = "/";
    };

    return (
      <>
        <Button
          onClick={() => signIn("google")}
          size="sm"
          variant="default"
          className="gap-1.5 text-xs shrink-0"
          title="Accedi con Google per sincronizzare i tuoi dati su tutti i dispositivi"
        >
          <LogIn className="h-3.5 w-3.5" />
          <span>Accedi</span>
        </Button>
        <Button
          onClick={() => setBetaDialogOpen(true)}
          size="sm"
          variant="outline"
          className="gap-1.5 text-xs shrink-0 hidden lg:inline-flex"
          title="Accedi come beta tester con un codice fornito dall'admin"
        >
          <KeyRound className="h-3.5 w-3.5" />
          <span className="hidden lg:inline">Beta</span>
        </Button>

        <Dialog open={betaDialogOpen} onOpenChange={setBetaDialogOpen}>
          <DialogContent className="sm:max-w-md">
            <DialogHeader>
              <DialogTitle className="flex items-center gap-2">
                <KeyRound className="h-4 w-4" />
                Accesso Beta Tester
              </DialogTitle>
              <DialogDescription>
                Inserisci la tua email e il codice che ti è stato fornito.
                Il codice può essere usato una sola volta.
              </DialogDescription>
            </DialogHeader>
            <div className="space-y-3 py-2">
              <div className="space-y-1.5">
                <Label htmlFor="beta-email">Email</Label>
                <Input
                  id="beta-email"
                  type="email"
                  placeholder="tuamail@example.com"
                  value={betaEmail}
                  onChange={(e) => setBetaEmail(e.target.value)}
                  disabled={betaLoading}
                  onKeyDown={(e) => { if (e.key === "Enter") handleBetaLogin(); }}
                />
              </div>
              <div className="space-y-1.5">
                <Label htmlFor="beta-code">Codice Beta</Label>
                <Input
                  id="beta-code"
                  type="text"
                  placeholder="XXXXXXXX"
                  value={betaCode}
                  onChange={(e) => setBetaCode(e.target.value.toUpperCase())}
                  disabled={betaLoading}
                  maxLength={8}
                  className="font-mono tracking-widest uppercase"
                  onKeyDown={(e) => { if (e.key === "Enter") handleBetaLogin(); }}
                />
              </div>
              {betaError && (
                <p className="text-sm text-destructive">{betaError}</p>
              )}
            </div>
            <DialogFooter>
              <Button
                variant="outline"
                onClick={() => setBetaDialogOpen(false)}
                disabled={betaLoading}
              >
                Annulla
              </Button>
              <Button onClick={handleBetaLogin} disabled={betaLoading}>
                {betaLoading ? "Verifica…" : "Accedi"}
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </>
    );
  }

  // Authenticated — show avatar + dropdown
  const user = session.user!;
  const displayName = user.name || user.email || "User";
  const isBetaCode = (session as any).isBetaCode === true;
  const initials = (user.name || user.email || "U")
    .split(" ")
    .map((s) => s[0])
    .slice(0, 2)
    .join("")
    .toUpperCase();

  return (
    <div className="relative" ref={menuRef}>
      <button
        onClick={() => setMenuOpen(!menuOpen)}
        className="flex items-center gap-1.5 rounded-full pl-1 pr-2 py-1 hover:bg-secondary/50 transition-colors"
        title={user.email || displayName}
      >
        {user.image ? (
          // eslint-disable-next-line @next/next/no-img-element
          <img
            src={user.image}
            alt={displayName}
            className="w-7 h-7 rounded-full border border-border/50"
            referrerPolicy="no-referrer"
          />
        ) : (
          <div className={`w-7 h-7 rounded-full ${isBetaCode ? "bg-amber-500/20 text-amber-600 border-amber-500/30" : "bg-primary/20 text-primary border-primary/30"} flex items-center justify-center text-xs font-bold border`}>
            {initials}
          </div>
        )}
        <ChevronDown className="h-3 w-3 text-muted-foreground hidden sm:block" />
      </button>

      {menuOpen && (
        <div className="absolute right-0 top-full mt-1 w-64 rounded-lg border border-border/50 bg-popover shadow-lg z-50 overflow-hidden">
          <div className="p-3 border-b border-border/30">
            <div className="flex items-center gap-2">
              {user.image ? (
                // eslint-disable-next-line @next/next/no-img-element
                <img
                  src={user.image}
                  alt={displayName}
                  className="w-10 h-10 rounded-full border border-border/50"
                  referrerPolicy="no-referrer"
                />
              ) : (
                <div className={`w-10 h-10 rounded-full ${isBetaCode ? "bg-amber-500/20 text-amber-600 border-amber-500/30" : "bg-primary/20 text-primary border-primary/30"} flex items-center justify-center text-sm font-bold border`}>
                  {initials}
                </div>
              )}
              <div className="min-w-0 flex-1">
                <div className="text-sm font-medium truncate">{displayName}</div>
                {user.email && (
                  <div className="text-xs text-muted-foreground truncate">
                    {user.email}
                  </div>
                )}
                {isBetaCode && (
                  <div className="text-[10px] mt-0.5 inline-flex items-center gap-1 px-1.5 py-0.5 rounded bg-amber-500/10 text-amber-600 font-medium">
                    <KeyRound className="h-2.5 w-2.5" />
                    Beta Tester
                  </div>
                )}
              </div>
            </div>
          </div>
          <div className="p-1">
            <button
              onClick={() => {
                setMenuOpen(false);
                // ⚠️ CRITICAL — Multi-user isolation:
                // Wipe ALL local data BEFORE signOut so the next user on
                // this device starts fresh. Without this, user A's demos,
                // profile, label emails, and saved pitches would leak into
                // user B's session when they log in next.
                // (useAuthEffect also clears on status→unauthenticated as a
                // safety net, but doing it here ensures it happens even if
                // the redirect races the effect.)
                try {
                  clearAllLocalData();
                } catch (e) {
                  console.warn("[AuthButton] Error clearing local data on logout:", e);
                }
                signOut({ callbackUrl: "/" });
              }}
              className="w-full flex items-center gap-2 px-3 py-2 rounded-md text-sm text-muted-foreground hover:text-foreground hover:bg-secondary/50 transition-colors"
            >
              <LogOut className="h-4 w-4" />
              Esci
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
